### ISSUE TITLE
pick list for age of onset

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-phenote#35] opened 2016-04-14 22:53 UTC
It is not immediately obvious what to put in "age of onset".
Typing "birth" for instance, does nothing because it expects "congenital".
Not sure how many age terms there are, but loading all of them into a combination autocomplete and dropdown might be the best compromise.
Additionally, having autocomplete start with one typed letter (rather than 3) may in this instance be preferred.

**Comment by cmungall** [comment] 2016-04-15 00:14
The general case is intended to be covered here: https://github.com/geneontology/noctua/issues/150

With each slot being configured by category

Age of onset is a good place to start for this

**Comment by DoctorBud** [comment] 2016-05-23 19:29
The AgeOfOnset autocomplete field is working as intended in my PR (not yet merged): https://github.com/geneontology/noctua/pull/307

**Comment by DoctorBud** [comment] 2016-06-01 12:09
Closing this issue. AgeOfOnset is working as intended now.

**Closed as completed by DoctorBud** 2016-06-01 12:09 UTC
